### ISSUE TITLE
Support downloading of non-streamable content types

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbrytv#115]
For files that cannot be streamed, have the streaming URL return the appropriate response headers for download (presumably `content-disposition: attachment; filename=<suggested_file_name>`)

**Comment by sayplastic** [comment]
This is done in lbrytv code already: any stream that has `download=1` query parameter appended to its URL will be sent as a downloadable file. @seanyesmunt is there anything that is needed to be done on the UI side?
