### ISSUE TITLE
Implement SDK Balance for non user specific calls

### ISSUE THREAD

**Issue by tiger5226** [lbryio/lbrytv#119]
Currently at https://github.com/lbryio/lbrytv/blob/master/app/router/router.go#L169 we are just grabbing the default SDK. We need to implement a more comprehensive method of getting SDKs that are in low use for these calls. 

I am not certain how yet, but I assume we can figure out or track the usage of an SDK so we can always grab the one that is used the least. This will also distribute the demand on the site.

**Comment by sayplastic** [comment]
We're going to have to monitor SDK instances health internally. Should not be hard to do based on various method response times, which are already tracked. In the meantime, an easy/obvious start would be to just grab a random server from the list of available.
