### ISSUE TITLE
Upload sitemap to Google Search Console

### ISSUE THREAD

**Issue by finer9** [lbryio/lbrytv#120]
I recently cleaned up our Search Console - there is now only one lbry.tv property and it is set up correctly.  While it seems to be indexing about 4k pages, I think we can get it to index more if we feed it properly.

**Comment by kauffj** [comment]
@finer9 @nikooo777 did this get done?

**Comment by kauffj** [comment]
@finer9 are you happy with results from this?

**Comment by finer9** [comment]
Yes our indexed pages and traffic from goog organic increased substantially. I do think we can get more pages in there

**Comment by nikooo777** [comment]
I updated the sitemaps and used 90k urls in total

**Comment by kauffj** [comment]
@nikooo777 is this in a place where we can forget about it? Is there any ongoing or leftover work?
