### ISSUE TITLE
lazy load wallets on startup

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbrytv#125]

**Comment by tiger5226** [comment]
Is this an SDK param @tzarebczan ? If you tell me it, I can test it out to make sure it doesn't have any user implications.

**Comment by tzarebczan** [comment]
No, the proxy needs to load them based on user activity.

**Comment by sayplastic** [comment]
@tzarebczan I have a feeling this is solved by https://github.com/lbryio/lbrytv/pull/138
