### ISSUE TITLE
Error message: There was a problem with your upload

### ISSUE THREAD

**Issue by gitkiwikiwi** [lbryio/lbrytv#143]
I tried to upload a mp4 format video on https://lbry.tv/ , but got this error. How to fix it?

Error
We're sorry that LBRY has encountered an error. This has been reported and we will investigate the problem.

Error message: There was a problem with your upload

**Comment by tzarebczan** [comment]
Sorry to hear about the trouble. Where are you located? Have you tried clearing it out and attempting the upload again? How big was the file? I tried one here and it seemed to work. 
If this continues, please send us an email to hello@lbry.com with your account information so we can take a closer look.
