### ISSUE TITLE
Support webm and AV1 rollalty free codecs.

### ISSUE THREAD

**Issue by paju1986** [lbryio/lbrytv#151]
mp4 is covered in patents and royalies, it would be good to support the open source rollalty free formats like webm and av1. Also av1 is considered better than HEVC itself.

**Comment by m4nnerheim** [comment]
I second this!

**Comment by tzarebczan** [comment]
Have you tried to upload something with this format? It may already work. If not, we don't plan to do this anytime soon. Mp4 is widely supported and most creators are familiar with it. Thank you for the suggestion.
