### ISSUE TITLE
LBRY.tv thinks my cell number is a voip phone.

### ISSUE THREAD

**Issue by Eviepayne** [lbryio/lbrytv#153]
Without telling you my number this is the message I'm getting:
![vivaldi_UqEsEM9pN4](https://user-images.githubusercontent.com/59463208/72775773-aaf1b580-3bdd-11ea-9c7b-f170a8c3949d.png)
Proof it's my android:
![Screenshot_20200120-233631](https://user-images.githubusercontent.com/59463208/72775886-19367800-3bde-11ea-90b9-de4593715c26.png)

**Comment by tzarebczan** [comment]
Sorry to hear about the issue. We mention this on the phone verification page - Canada has some strict laws around using a phone number to authenticate users. 

Send us an email at hello@lbry.com and we'll get you rewards approved.
