### ISSUE TITLE
add an endpoint to force frontend reload

### ISSUE THREAD

**Issue by nikooo777** [lbryio/lbrytv#157]
When lbrytv updates old clients don't update to the new version until they refresh the page. this might take a long time, even days if the users never close their tabs.
the APIs should offer an endpoint that accepts a parameter (like the time the client last fetched the frontend or the version of the frontend running locally) and return a flag that indicates whether the client should reload its tab.

**Comment by sayplastic** [comment]
Backend API has no idea when the frontend is updated. This should be handled on the javascript side.
