### ISSUE TITLE
cache authentication token

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbrytv#162]
If I understand correctly, we calls apis on every single call that needs an auth token before passing it to the proxy. If this is true, we are really hammering apis with requests. Tokens don't change or invalidate that often, so they should be at least cached for a few minutes.  See discussion on slack in #tech

The only corner case I can think of is with user merges - a user may go from 12345 to 23456 if their accounts are merged, so we do need awareness of that. If it takes a few minutes, not a big deal.

**Comment by sayplastic** [comment]
I would really like to avoid cache whenever possible. Why introduce a point of complexity/failure to this chain?

`lbrytv -> internal-api -> db`

Can you define "hammering"? What exactly is internal-apis struggling with? 

The auth endpoint normally responds within 50ms. It is very simple, DB query should be the most resource-intensive part of this chain and it is just a single record `SELECT` against one table.

**Comment by lyoshenka** [comment]
we'll have exact numbers after lbryio/internal-apis#1223 is merged

**Comment by sayplastic** [comment]
On the lbrytv side I'm seeing 120 requests per second.

**Comment by kauffj** [comment]
still consider soon?

**Comment by andybeletsky** [comment]
Done on the internal-apis side, according to @nikooo777
