### ISSUE TITLE
Show preview on unsupported file formats

### ISSUE THREAD

**Issue by rainbowjaw** [lbryio/lbrytv#165]
If you take this post as an example you can see how LBRY.TV shows now preview file, if sent as a link then the user has no idea what they are looking at:
https://open.lbry.com/@Sol-art-archive:a/ballet:8?r=Cs2WAZHpMqPTuFiVjF3YzewoXMwoBc4Q
![lbry tv](https://user-images.githubusercontent.com/39452251/73896683-b7b71000-4851-11ea-945f-6cb479263bf1.PNG)

I'm mirroring this issue from the desktop app repository: https://github.com/lbryio/lbry-desktop/issues/3644
but a full solution would be something like this:
![previewsupported2](https://user-images.githubusercontent.com/39452251/73896577-5abb5a00-4851-11ea-8f53-fca83d2dda24.jpg)

Text should be what ever makes sense "click here to download this file" or what ever.

**Comment by tzarebczan** [comment]
Thanks! This should be filed on the desktop repo, all the code is shared.
