### ISSUE TITLE
Gif vs Webm on animated video thubnails

### ISSUE THREAD

**Issue by MasterPCUK** [lbryio/lbrytv#167]
Hello
I noticed that gif images on thumbnails are huge at 3.2mb. Any reasons why WebM isn't used as it offers 95% file size reduction?

Btw, what a lovely project this is!

**Comment by tzarebczan** [comment]
Thanks for the issue. Normally these should be opened under lbry-desktop repo. 

We'll have to explore if this is possible as a thumbnail and users would need to create them in that format vs a GIF. Right now you can't set a webm and have it render as a thumb.

**Comment by tzarebczan** [comment]
Issue moved to [lbryio/lbry-desktop #3659](https://github.com/lbryio/lbry-desktop/issues/3659) via [**ZenHub**](https://www.zenhub.com/)
