### ISSUE TITLE
Direct resolve and claim_search requests to a separate SDK instance

### ISSUE THREAD

**Issue by andybeletsky** [lbryio/lbrytv#172]

**Comment by andbeletsky** [comment]
Worth to keep #174 in mind

**Comment by tzarebczan** [comment]
This may not be possible if/once we start using claim search/resolve along with wallet_id. This would be used to show purchase receipts or having awareness of your own claims in those calls. There are workaround like passing the claim ids to txolist / claim list instead.

**Comment by andybeletsky** [comment]
We should temporarily put this on hold.

**Comment by andybeletsky** [comment]
Not needed anymore as resolves and claim search can accept wallet_id now.
