### ISSUE TITLE
Add support for two bit rates per stream: "low" 480p and "high" 1080p

### ISSUE THREAD

**Issue by eukreign** [lbryio/lbrytv#190]
The SDK part of this is defined here: https://github.com/lbryio/lbry-sdk/issues/2879

- [ ] download both the high definition and low definition blobs/file for a claim
- [ ] when app requests videos to play it will pass which versions of the video should play, lbrytv should return the correct version

**Comment by andybeletsky** [comment]
This is currently done via transcoding.
