### ISSUE TITLE
Player add navigation hotkeys

### ISSUE THREAD

**Issue by javalight** [lbryio/lbrytv#191]
Some useful hotkeys that the youtube player implements would be great to have like: 

- j = back 10s
- l = forward 10s
- 0 = go to beginning of video
- 1 = go to 10% of video 
- 2 = go to 20% of video
- ...
- 9 = go to 90% of video

I use these hotkeys constantly, would be nice to see them in LBRY.

**Comment by tzarebczan** [comment]
Thanks for the issue! You can direct future ones in lbry-desktop repo but please do a scan of existing issues or check with us at chat.lbry.

We have some available, but it's not clear that they are: https://github.com/lbryio/lbry-desktop/issues/3041

Other shortcuts issue: https://github.com/lbryio/lbry-desktop/issues/1395
