### ISSUE TITLE
A/B Cluster improvements (claim search / trending algos)

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbrytv#194]
- [x] users with wallets on cluster A should hit claim search (that's the most important, but we can make it all calls) on cluster A servers
- [ ] unauth users should somehow stick to a single cluster they start in - so maybe just use A or B for them?

**Comment by andybeletsky** [comment]
Blocked until #196 is merged

**Comment by tzarebczan** [comment]
To finish this off, we'd pass the trending algo from the status call on the SDKs (See below). We would probably only want to call this on startup and save somewhere vs calling status al the time.

``` "wallet": {
    "available_servers": 1,
    "best_blockhash": "76d8290630ef729e9ca8b2551d705ee1a4459bc72a33a44aba06a41a0f847133",
    "blocks": 789128,
    "blocks_behind": 0,
    "connected": "3.6.203.8:50001",
    "connected_features": {
      "daily_fee": "0",
      "description": "",
      "donation_address": "",
      "genesis_hash": "9c89283ba0f3227f6c03b70216b9f665f0118d5e0fa729cedf4fb34d6a34f463",
      "hash_function": "sha256",
      "hosts": {},
      "payment_address": "",
      "protocol_max": "0.99.0",
      "protocol_min": "0.54.0",
      "pruning": null,
      "server_version": "0.76.0",
      "trending_algorithm": "ar"
    },```

**Comment by andybeletsky** [comment]
Please reopen if needed again.
