### ISSUE TITLE
Some videos refuse to play in Brave browser

### ISSUE THREAD

**Issue by eggplantbren** [lbryio/lbrytv#205]
I had some webm videos on my channel that won't play in Brave, and I thought replacing them with MP4s would fix the problem, but it didn't. For example, at https://lbry.tv/@BrendonBrewer:3/house-ad:8 I get this error:

![image](https://user-images.githubusercontent.com/1578298/80159839-1bb2ce80-8620-11ea-941d-7c0f7464ce35.png)

I know Brave is a minority browser, but this should work.

Weirdly, [this video](https://lbry.tv/@BrendonBrewer:3/metropolis:f), which I encoded using virtually identical settings, works.

For testing purposes, https://lbry.tv/testingtesting:e is a version without dashes in the filename or claim name (not sure if this is related to the problem or not), and https://lbry.tv/testingtesting2:1 is a version where I said "yes" to the LBRY transcoding option.

**Comment by andybeletsky** [comment]
Brave is blocking the video because there's "ad" in the url — it is mentioned in the Brave Shields if you click on it.
