### ISSUE TITLE
Embed HTML code doesn't work

### ISSUE THREAD

**Issue by adnan360** [lbryio/lbrytv#208]
I put the Embed code from the share option of [this video](https://lbry.tv/@lbry:3f/lbry2youtubetest:f). The html code for test is:

```html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<title></title>
	</head>
	<body>
		<iframe width="560" height="315" src="https://lbry.tv/$/embed/lbry2youtubetest/f26f82457cfe29146823bd11df0c58a004252b4e" allowfullscreen></iframe>
	</body>
</html>
```

I tried both locally and on an online server. Both renders a grey box instead of the player showing. Tried on Firefox and Brave. Both got same results (screenshots attached).

![lbry-embed-01](https://user-images.githubusercontent.com/7857310/80353977-f3350980-8897-11ea-86bd-a6169d5ead7c.png)
![lbry-embed-02](https://user-images.githubusercontent.com/7857310/80353996-f7612700-8897-11ea-8a73-7119be90e082.png)

**Comment by tzarebczan** [comment]
Sorry for the late reply, this PR should fix it: https://github.com/lbryio/lbry-desktop/pull/4206
