### ISSUE TITLE
Race condition during new user creation

### ISSUE THREAD

**Issue by andybeletsky** [lbryio/lbrytv#209]
Wallet package is throwing an error:

```
unknown error encountered while creating user: pq: duplicate key value violates unique constraint
```

This should be handled by `pgUniqueConstraintViolation` conditional but for some reason isn't.

**Comment by andybeletsky** [comment]
cc @lyoshenka

**Comment by lyoshenka** [comment]
i believe this is fixed now. if you see it again, plz send me a link to sentry or wherever you see it
