### ISSUE TITLE
Videos fail to play at the very end

### ISSUE THREAD

**Issue by sayplastic** [lbryio/lbrytv#21]
![image.png](https://images.zenhubusercontent.com/5ba107c3926ebd396bd72777/13f1cede-b493-4590-9976-7de5cfd07aac)

**Comment by sayplastic** [comment]
I cannot understand why it fails, the server certainly delivers every byte it promises in the headers. Also not reproducible on every video.

Here's an example of a video that fails:

https://piratebay.com/heading-back-to-arizona-bus-life-skoolie/100e72fe19870422b66a3bee3d7b8069d86fed13

Here's an example of a video that doesn't:

https://piratebay.com/what/6769855a9aa43b67086f9ff3c1a5bacb5698a27a

**Comment by tzarebczan** [comment]
This works well with SDK streaming + lbry.tv - streams til the end, and stops.

**Comment by sayplastic** [comment]
I compared video files downloaded via lbrytv and via app for the erroring video, they were identical.

@seanyesmunt would it be possible to get some more debugging ouput from the video player besides this? Or even suppress the error completely.

```
ui.js:29 VIDEOJS: ERROR: (CODE:3 MEDIA_ERR_DECODE) The media playback was aborted due to a corruption problem or because the media used features your browser did not support.
```

**Comment by sayplastic** [comment]
This has been finally resolved after the recent player module overhaul.
