### ISSUE TITLE
support both authenticated and unauthenticated resolve calls

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbrytv#212]
We may want to do this for claim search also.

**Comment by jessopb** [comment]
This is blocking for a pr. 
I've added --include_is_my_output to resolve when resolving only one claim. I'd also like to add the flag to claim_search at least on the page displaying channel content - people need to see what content is blocked and we use whether it is theirs to decide whether to ignore blocking (so they can delete their blocked claim). Probably these only need to be authenticated/wallet -specific when that flag is passed. But maybe we want to pass the flag every time when sdk db rewrite is finished. 

If there isn't a better way, we could selectively call different apis from the app in different circumstances.
