### ISSUE TITLE
Analytics for LBRY.TV

### ISSUE THREAD

**Issue by tiger5226** [lbryio/lbrytv#22]
Hi guys, I was talking with Josh about getting the right calls for analytics in lbrytv. Not sure what you guys have done here on this.

Currently we link users from web properties like lbry.com via the following code:

https://github.com/lbryio/lbry.com/blob/9d09248bd0466f8dd527a1d89fe34a404d2bf624/view/template/layout/_analytics_footer.php#L13-L17

https://github.com/lbryio/lbry.com/blob/9d09248bd0466f8dd527a1d89fe34a404d2bf624/controller/Session.class.php#L34-L48

The basic flow is to capture the GA client id, pass it to internal-apis which logs it as a web visitor. Then tries to link the IP address to users. Once a link is made special events are pushed to google analytics like searches and views.

Since this is a website, I would assume you could just do this directly in the code. However, since we are sharing a codebase, it might be better to use the method built for lbry.com. I would like to hear your thoughts though. Ultimately, we would like to have this setup for Josh before we go live, so he has access to the important information.

I spoke with @seanyesmunt about the above in slack channel #analytics-lbrytv

>Anything in the browser, we can do in electron. They are treated the exact same way as far as individual page tracking and event tracking. We should be able to do the same tracking as we do on lbry.com.

I assigned all parties. I put the issue here since it is directly related to lbry.tv and made it a blocker for when we switch it back over to users so we can get some information that is comparable to the desktop app.

**Comment by kauffj** [comment]
This was resolved in lbry-desktop. Please re-open if you think this is incorrect.
