### ISSUE TITLE
Ditch usage of Google Captcha

### ISSUE THREAD

**Issue by pluja** [lbryio/lbrytv#221]
As a free (as in freedom) platform seeking to respect its users, stopping the use of Google Captcha and using other privacy-respecting captchas or even your own captcha would be great.

(Google Captcha seen when confirming an account)

**Comment by tzarebczan** [comment]
Thanks for the issue. We have the captcha issue filed internally and lbry.tv changes under : https://github.com/lbryio/lbry-desktop/issues/4062
