### ISSUE TITLE
Strip Markdown Out of Meta Descriptions

### ISSUE THREAD

**Issue by Invariant-Change** [lbryio/lbrytv#230]
**Meta Description carries over MarkDown.** 

![image](https://user-images.githubusercontent.com/29914179/83329054-7ea41f00-a2ca-11ea-8eb0-67037266cf4b.png)

It would be good to strip it out with something like `text.replace(/[\W_]+/g," ");`

This is will look much better and be SEO friendly.

**RegEx Result**: https://regex101.com/r/t9z3gw/2

**Comment by tzarebczan** [comment]
This is filed on Desktop already. LBRY.tv repo is just the proxy for sdk , all code is on desktop.

**Comment by Invariant-Change** [comment]
Oh yeah I see it [here](https://github.com/lbryio/lbry-desktop/issues/3575).
I assumed it would be LBRY TV only because only websites use OG and meta tags. I'll link this one under your current one on desktop issues for furth info.
