### ISSUE TITLE
File type should be recognized even without extension in file name

### ISSUE THREAD

**Issue by alojzjakob** [lbryio/lbrytv#238]
it forces me to download the file, because lbry cant display it, since there is no extension to recognize file type.

**Comment by tzarebczan** [comment]
Can you give us an example of the file/claim? I don't think you can upload something now without a file extension....

There is a known issue on Firefox with a file name that has spaces in it - maybe that's what you ran into?

**Comment by alojzjakob** [comment]
I dont have an example now, I created this issue when @CryptoHustler101 published a video vithout extension, so he needed to reupload because it couldn't be played.

**Comment by tzarebczan** [comment]
Closing for now, it should not be possible to upload a file without an extension.
