### ISSUE TITLE
og:image needs to match content

### ISSUE THREAD

**Issue by jsigwart** [lbryio/lbrytv#25]
## The Issue

Currently the og:image set for any piece of content is:
![og:image](https://beta.lbry.tv/og.png)

The app should use the thumbnail provided with the content unless it has no thumbnail then should use the above by default.

**Comment by tzarebczan** [comment]
This is filed on the desktop side https://github.com/lbryio/lbry-desktop/issues/2410

This repo would be for issues specific to streaming or authentication.
