### ISSUE TITLE
Current roadblocks for experimental SDK

### ISSUE THREAD

**Issue by andybeletsky** [lbryio/lbrytv#254]
First priority issues:

- [x] `resolve` of `lbry://@healthdear#e/right-attitude-to-success#a` results in `invalid channel signature`
  - PR open https://github.com/lbryio/lbry-sdk/pull/3039
- [x] Error 500 on requests with unknown or invalid parameters
- [x] Reverse compatibility mechanisms (i.e. column `effective_amount` is not currently recognized)
- [x] [Resolve discrepancies](https://sentry.lbry.tech/organizations/lbry/issues/6730/?project=3&query=is%3Aunresolved)

Non-blocking issues:

- [x] Proper exit procedure: while the main process quits, forked procedures are still staying in place (`Ctrl+C` doesn’t work as well)
- [x] ZMQ readiness detection (currently just quits if lbrycrd isn't ready for ZMQ requests)
  - PR open: https://github.com/lbryio/lbry-sdk/pull/3040
- [x] Traces are being logged in full instead of one-line entries (ideally they should be sent to Sentry for easier analysis)
- [ ] Cryptic logging that doesn't indicate where SDK is at currently (example: `lbrynet INFO:lbry.blockchain.lbrycrd:b'93efe9e752bfcc2c3721e51675224cd915b9b7bef58c09013a5cedb49243619e' 36`)

**Comment by kauffj** [comment]
@andybeletsky this is not expected to be completed:

> Cryptic logging that doesn't indicate where SDK is at currently (example: lbrynet INFO:lbry.blockchain.lbrycrd:b'93efe9e752bfcc2c3721e51675224cd915b9b7bef58c09013a5cedb49243619e' 36)

Please speak up if this is still a priority issue for you.

**Comment by kauffj** [comment]
Closing this with the understanding `claim_search` must still be fixed. Some URL discrepancies remain but they are trivial and acceptable.

**Comment by lyoshenka** [comment]
continuing discussion here https://github.com/lbryio/lbrytv/issues/294
