### ISSUE TITLE
Feature Request: Ability to upload videos in mass to lbry.tv via BitTorrent

### ISSUE THREAD

**Issue by Electricianfromhell** [lbryio/lbrytv#262]
I would love lbry.tv to have the ability to take video uploads in mass batches via bit torrent via a torrent file to upload videos in batches to lbry.tv channels via BitTorrent similar to how bit torrent can be used to upload files in batches or mass to the internet archive.

the way this should work is

you put all the video files in one folder you want to upload and create a new torrent file of that folder

you enter trackers for lbry into the torrent properties when you create the new torrent file

you let the new torrent file start seeding

you upload the .torrent file itself to your channel on lbry.tv

Lbry.tv from there downloads your videos over BitTorrent and puts your videos on the lbry.tv network under the channel you selected to upload the .torrent file you created to seed the files.

**Comment by tzarebczan** [comment]
Thanks for filing this issue! We have some basic torrent support on the SDK side but it's not working with lbry.tv and probably won't be for some time. We may consider this down the road. 

We're also looking into the ability to add multiple files along side a single claim which could help the multiupload scenario.
