### ISSUE TITLE
In recomended videos, do not list the "Already seen videos"

### ISSUE THREAD

**Issue by aboimpinto** [lbryio/lbrytv#280]
Don't know if this is the right place to place this issue, but, here it goes.

I didn't check what the API exposes or not but one thing would be great (and less annoying when watching the Recent from following videos list) is excluding the already seen videos.

There could be an option that lets the developer decide if they are shown or not and provide an interaction with the user that will decide if he wants to list the already seen or not.

In my current "Recent from following" I'm full of already seen videos.

hope this is not very complicated to implement.
Best wishes and keep the good work
Paulo Aboim Pinto

**Comment by tzarebczan** [comment]
Thanks for filing this issue. We'd need to implement https://github.com/lbryio/lbry-desktop/issues/3614 to do this. 

The right place in the future would be the lbry-desktop repo (I know, the name is confusing, but the desktop app shares the same code as lbry.tv). This repo is mainly for api interactions between the front and backend. 

Thanks again and take care!
