### ISSUE TITLE
My account keeps resting to its default state.

### ISSUE THREAD

**Issue by Mvcvalli** [lbryio/lbrytv#283]
**What happened:** 

The wallet was synced normally, but the channels I follow did not sync and "are gone". And now the channels are also gone from the website and the app.

This has happened to me four times now once when using the LBRY app on MacBook Pro Retina, 15-inch, Mid 2015 and three times when using the lbry.tv website. I use the Brave Browser.

**Comment by tzarebczan** [comment]
Sorry to hear, this is a known bug in some rare cases. I replied on Reddit with what the next steps are and for additional information. Please give us a reply there.
