### ISSUE TITLE
How to run this without Docker?

### ISSUE THREAD

**Issue by probonopd** [lbryio/lbrytv#295]
I want to run this on a small ARM-powered device which has no place for Docker.
Downloaded and built it with go, but then? How to __use__ it?

```
FreeBSD% /home/liveuser/go/bin/lbrytv 
{"buildCommit":"unknown","buildDate":"unknown","buildVersion":"unknown","level":"info","logLevel":"info","mode":"production","msg":"standard logger configured"}
{"level":"info","module":"monitor","msg":"sentry disabled (no DSN configured)"}
{"dsn":"postgres://lbrytv:lbrytv@localhost/lbrytv?sslmode=disable","level":"info","module":"storage","msg":"connecting to the DB"}
{"dsn":"postgres://lbrytv:lbrytv@localhost/lbrytv?sslmode=disable","level":"info","module":"storage","msg":"DB connection failed"}
panic: dial tcp [::1]:5432: connect: connection refused

goroutine 1 [running]:
main.main()
        /home/liveuser/lbrytv/main.go:41 +0x766
FreeBSD% /home/liveuser/go/bin/collector 
{"buildCommit":"unknown","buildDate":"unknown","buildVersion":"unknown","level":"info","logLevel":"info","mode":"production","msg":"standard logger configured"}
{"dsn":"postgres://collector:ZnPfJ!4vTb-nURv8M!JkkuAcjYLYbkiX@localhost:5433/collector?sslmode=disable","level":"info","module":"storage","msg":"connecting to the DB"}
{"dsn":"postgres://collector:ZnPfJ!4vTb-nURv8M!JkkuAcjYLYbkiX@localhost:5433/collector?sslmode=disable","level":"info","module":"storage","msg":"DB connection failed"}
panic: dial tcp [::1]:5433: connect: connection refused

goroutine 1 [running]:
github.com/lbryio/lbrytv/apps/environment.ForCollector(0xc74940)
        /home/liveuser/lbrytv/apps/environment/apps.go:22 +0x3b0
github.com/lbryio/lbrytv/apps/collector/cmd.glob..func3(0x1170d20, 0x11ac458, 0x0, 0x0)
        /home/liveuser/lbrytv/apps/collector/cmd/serve.go:19 +0x26
github.com/spf13/cobra.(*Command).execute(0x1170d20, 0xc000032200, 0x0, 0x0, 0x1170d20, 0xc000032200)
        /home/liveuser/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:846 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0x1170d20, 0x8bcc83b7490, 0x476aef, 0xc000110000)
        /home/liveuser/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        /home/liveuser/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
github.com/lbryio/lbrytv/apps/collector/cmd.Execute()
        /home/liveuser/lbrytv/apps/collector/cmd/serve.go:32 +0x31
main.main()
        /home/liveuser/lbrytv/apps/collector/main.go:16 +0x8a
```

Related: https://github.com/accumulator/plugin.video.lbry/issues/3

**Comment by tzarebczan** [comment]
What is is you want to run exactly? This repo is for a public lbry.tv api which would support websites like lbry.tv. 

Maybe you're looking for the lbry-desktop repo, but don't think the sdk runs on arm devices without having it built there manually.

**Comment by probonopd** [comment]
Well, I am looking for "the API Server" that is apparently required to watch Lbry on [KODI](https://kodi.tv/).

**Comment by tzarebczan** [comment]
It can use the public api we have running on api.lbry.tv

Also, maybe check out https://amp.reddit.com/r/lbry/comments/k40w1q/kodi_plugin_for_lbry/ ?

**Comment by probonopd** [comment]
> Also, maybe check out https://amp.reddit.com/r/lbry/comments/k40w1q/kodi_plugin_for_lbry/ ?

Yes, this exact plugin is the reason that I am asking, because it asks for an "API Server" to be used:
https://github.com/accumulator/plugin.video.lbry/issues/3

**Comment by tzarebczan** [comment]
Give that a try, should work. The other option would be to run the lbry-sdk on the device itself, or on another device on the network and allow external access (would need to run api server on 0.0.0.0)

**Comment by probonopd** [comment]
Entered `https://api.lbry.tv` without a port number, gave an error message. Will look at the log now.

**Comment by tzarebczan** [comment]
You can see how they are called in the network tab on lbry.tv

I don't think it was intended to work with the public api, but a local one with a running on the device. 

You can try api.lbry.tv/api/v1/proxy instead.

**Comment by probonopd** [comment]
Incredible! This __works__! Thank you so very, very much. :+1: :100: :1st_place_medal:

**Comment by tzarebczan** [comment]
Woohoo, I'm glad to hear that! If you find the time, please comment on his repo with the details. Maybe he can make that the default since most folks wouldn't need to run a local sdk.

**Comment by probonopd** [comment]
The pull request above does exactly that @tzarebczan. Thank you for your help.

**Comment by tzarebczan** [comment]
No, thank you! Shoot me over your LBC address on Twitter Dm (@tomzarebczan) and we'll get a tip over :)
