### ISSUE TITLE
[REQUEST] RSS

### ISSUE THREAD

**Issue by FatBirdie** [lbryio/lbrytv#299]
Since all pages are dynamically generated with JS, I would like to request a RSS service for lbry.tv to get channel updates instead of having to log into the website/account in order to keep track of new videos from creators.
RSS makes things so much easier, and not everyone wants an account either. Really hope this can be implemented in the future.

**Comment by tzarebczan** [comment]
There's a separate issue filed on the lbry-desktop repo which is the front end and main lbry.tv server. Thank you for the feature request!

**Comment by FatBirdie** [comment]
I mean, I'm sure the third party works, but having to set up that whole thing in comparison to just doing a wget/curl. Not worth it. Not really what I imagine when handling RSS feeds. Normally there is just a small "RSS" icon, with an url, copy/paste into the RSS reader and you're set to go.

Hope you fix this in the future anyway.
