### ISSUE TITLE
increase timeout on txo spend / txo list

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbrytv#301]
We need to increase http timeouts for JSON-RPC methods `txo_spend`, `txo_list` and `transaction_list` as some of them can take 5+ minutes to run. 

This can be done by creating a new http client for each new `query.Query` to be sent.

The SDK team [will look to make methods more performant](https://github.com/lbryio/lbry-sdk/issues/3168).

**Comment by tzarebczan** [comment]
Can we have this setp for txo spend? 
 A VIP creator recently ran into this problem. The txo spend took 2+ hours due to a huge history.

**Comment by tzarebczan** [comment]
Other creators have run into this. WhenI did some testing, it can take hours to run for really large wallets.

**Comment by camccar** [comment]
Pull request to for this change.

https://github.com/lbryio/lbrytv/pull/325

**Comment by andybeletsky** [comment]
Done, thank you @camccar

**Comment by andybeletsky** [comment]
sorry @camccar, it slipped my attention that we were fixing the wrong timeout, `http.Client.Transport.ResponseHeaderTimeout` was the one to fix. I also [added a test for it](https://github.com/lbryio/lbrytv/pull/326/files#diff-d3157f16027f9ae172ae544416eb3211dadc009bf07fbfe1264341324b02a04fR546), in case you are curious.

**Comment by camccar** [comment]
> sorry @camccar, it slipped my attention that we were fixing the wrong timeout, `http.Client.Transport.ResponseHeaderTimeout` was the one to fix. I also [added a test for it](https://github.com/lbryio/lbrytv/pull/326/files#diff-d3157f16027f9ae172ae544416eb3211dadc009bf07fbfe1264341324b02a04fR546), in case you are curious.

`TestCaller_timeouts`, That is a really cool unit test .
