### ISSUE TITLE
Support for LibreJS

### ISSUE THREAD

**Issue by JYamihud** [lbryio/lbrytv#312]
# Problem

A lot of GNU/Linux YouTubers moved to LBRY or synced with it at least. @Lunduke even deleted his YouTube videos. And now posts on LBRY exclusively. So I was surprised when on [FSF.org](https://www.fsf.org/share) in their Social Network recommendations they don't list LBRY. 

I know that the code of this web site is Free Software. But for most people the easy way to check it is to see whether the site runs under [LibreJS](https://www.gnu.org/software/librejs/). Or at least supports NON-JavaScript mode.

Me personally. I know that the license for the entire site is fine. So I whitelisted LBRY.TV and ODYSEE.COM in my LibreJS. GitHub for example works. But blocks 8 scripts.

On LBRY nothing loads. 1 script is blocked. [This one.](https://lbry.tv/public/ui-225aaf18-10ff-422f-bf90-99fc6ad91548.js) Which probably loads the rest of the site.

LibreJS works by evaluating the complexity of each JavaScript. And if it's anything more then trivial it checks for a License. And it does it for each script independently. If a script has no license. Or the license is [not Free](https://www.gnu.org/licenses/license-list.html). It blocks that script from running. 

By not putting a license into the text of the JavaScripts. We prevent a large amount of people from endorsing the platform. So a thing should be done about it. 

# How to fix the problem

To fix the problem we need to do next:

 - Install either [GNU IceCat Browser](https://www.gnu.org/software/gnuzilla/) or a LibreJS plugin for Firefox.
 - Go over the scripts that it refuses to load.
 - Put a license comment to them. 

Another possible solution:

 - Build an HTML-5 (zero JavaScript) version of the site. That might look terrible but will allow people to use it. It could be cool for people who use Tor and block ALL JavaScripts. Not only non-free ones.

**Comment by tzarebczan** [comment]
Thank you for the issue, this is filed under the front end at https://github.com/lbryio/lbry-desktop/issues/5327
