### ISSUE TITLE
Distribute rewards in batches rather than one by one

### ISSUE THREAD

**Issue by erkinalp** [lbryio/lbrytv#314]
Currently, each Odysee reward creates its own transaction with only one Odysee reward awarded, and with the remnant returned to Odysee. I would rather like to see them awarded in batches to fill the blocks as much as possible. This issue is *not* concerned with mining rewards, which cannot be changed without forking the blockchain.

**Comment by tzarebczan** [comment]
Thakns for reaching out. This issue is filed under another internal repo and we plan to do this for some rewards in the future. Right now there are no concerns about block sizes as they are not full.
