### ISSUE TITLE
odysee.com is missing "Show mature content" option.

### ISSUE THREAD

**Issue by fcolecumberri** [lbryio/lbrytv#322]
the lbry desktop app and lbry.ty have the option, but odysee.com is missing it.

Maybe this shouldn't be here, but I can't find odysee.com github page (maybe it is this page).

**Comment by tzarebczan** [comment]
There's an issue filed on the lbry-desktop repo (which is the Odysee front end) for this. We'll probably link to the desktop app, as mature content (mainly pornography) is not allowed on Odysee.

**Comment by fcolecumberri** [comment]
> as mature content (mainly pornography) is not allowed on Odysee.

😭😭😭 BUUUuuu 😭😭😭

(this message was not written to be taken seriously)
