### ISSUE TITLE
LATEST PUBLICATIONS DO NOT WORK!!!

### ISSUE THREAD

**Issue by JYamihud** [lbryio/lbrytv#328]
*It's 10:35 o clock. Jerusalem time.* I posted some things. And they are failing to load back. Both in Odysee and the LBRY Desktop. I'm not sure where to send this bug report. 

I checked new publications on the LBRY desktop. Just the most recent ones. And nothing from the very recent doesn't load. It's seems to be something to do with server side. That happened very not too far back. Like maybe an hour ago.

6 hour ago publications work fine. I don't know where is the line exactly. But I hope I was helpful for you to notice.  

# Please fix it. People can't upload anything new.

**Comment by JYamihud** [comment]
> it's 10:35 o clock
PM ( 22:35 )

**Comment by tzarebczan** [comment]
They should be working now, we had backlog and some slowness on the data network. Sorry for the trouble.
