### ISSUE TITLE
Modify file naming scheme to append random characters at end of file name

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbrytv#329]
https://github.com/lbryio/lbrytv/blob/master/app/publish/publish.go#L222

Append the random characters to the end of the original file name instead of the front. 

This way when a user downloads the files, they will have the title /claim name and then the random bits at the end.

**Comment by andybeletsky** [comment]
This has been solved with the help of @nheingit, original file names are now fully preserved.
