### ISSUE TITLE
Double Confirming Shows only 1 Confirm

### ISSUE THREAD

**Issue by bypiffa** [lbryio/lbrytv#339]
I was editing thumbnails for a large amount of videos in the same time. I click edit, change the thumbnail and click Apply. While this one is confirming I edit the next one. But when I hit apply for the next one, it should show that 2 videos are during confirming, but I see only 1 confirming. In the wallet I see 2 pending. Perhaps there is the a bug in the UI. Maybe there is no support for showing more than 1 confirming in the uploads page.

**Comment by tzarebczan** [comment]
This is a know bug on the sdk backend with showing multiple updates, sorry for the trouble! They all will go through once confirmed and will show at the top then.
