### ISSUE TITLE
Live stream let's me choose replay that is too big

### ISSUE THREAD

**Issue by bypiffa** [lbryio/lbrytv#340]
# Let's me choose 
![image](https://user-images.githubusercontent.com/74742244/119384959-21b92a00-bcce-11eb-93dc-7f68f63de18e.png)
# Let's me apply
![image](https://user-images.githubusercontent.com/74742244/119385018-3695bd80-bcce-11eb-9f3a-6a54f59277e3.png)
# Gives me an error
![image](https://user-images.githubusercontent.com/74742244/119385054-46150680-bcce-11eb-9122-f345caa18209.png)

**Comment by tzarebczan** [comment]
We shouldn't be allowing ones over 4 hours, we'll take a look. Your best bet right now would be to download the file and then transcode it down, or us the desktop app at lbry.com/get to publish.
