### ISSUE TITLE
Dockerize a personal instance

### ISSUE THREAD

**Issue by shyba** [lbryio/lbrytv#344]
(opening the issue here to track progress as it looks like the best place for now, but it is just something I am already doing and some ideas I brainstormed in the process for later)

Overview: have a way to quickly setup a custom owned lbrytv-like site while helping host/seed content.
Unlocks now:
    - having a way to seed content and help using remote machines
    - having p2p web gateways (what we call players currently, but p2p based and not video specific)
Later:
    - making content portals for channels or small communities
    - can be used as a reflection target, so you publish to your web node and it seeds the p2p content.
    - important piece for having a fully decentralized infra/node

## first goal
- [ ] Dockerfile that starts the SDK in this mode and the app in web mode without login
### steps
- [x] - SDK running with proper CORS
    - [x] check if there is an easy way to disable the wallet too
- [ ] - app without login components
    - [ ] remove login related components with a conf value, make a PR with it
    - [ ] document how to pick a logo and title

## later // nice to have:
- [ ] - buttons like "deploy to heroku/linode/vultr" where supported
- [ ] - ensure DHT port forwarding works
- [ ] - minimal admin interface (content pinning and daemon settings would be nice already)
    - [ ] content pinning: you pick what to store and what to stream/pipe. small list of what not to stream/pipe. (interacts with space management in that pinned content has priority when disk is full)

**Comment by kodxana** [comment]
```version: '3.3'
services:
    websdk:
        image: vshyba/websdk
	ports:
            - '52790:5279'
            - '52800:5280'
	volumes:
  	    - ./webconf.yaml:/webconf.yaml
  ```
  
 Docker-compose for SDK with exposed config file :)
