### ISSUE TITLE
Not all Spee.ch links work for downloading files

### ISSUE THREAD

**Issue by JYamihud** [lbryio/lbrytv#346]
I'm writing a peace of software, it's called [VCStudio](https://notabug.org/jyamihud/VCStudio). And I want to implement an Update system using [this channel](https://odysee.com/@blender-organizer:5) on LBRY. What I did a week or two ago is a little Markdown reader that would swap the `lbry://` to `spee.ch/` and download the article about the update. But currently it's not working. Gives either `Origin Offline` or `could not resolve stream URI`. 

For some articles and some files it works. But for other it doesn't. I think something about this way to retrieving files is broken. Can you please fix it?

**Comment by tzarebczan** [comment]
Please shoot us an email at hello@lbry.com with which links are not working.

**Comment by JYamihud** [comment]
But it's happening at random.

**Comment by tzarebczan** [comment]
Unfortunately, we would need more reproducible details to help.
