### ISSUE TITLE
Where can I found the odysee.com source code?

### ISSUE THREAD

**Issue by EuriNaiz** [lbryio/lbrytv#352]
I'm really interested to switch to odysee from youtube, but I want to be sure that odysee is fully libre (you're recommending to use odysee instead lbry.tv), so I have other additional question, have you in your plans to do odysee android and desktop app? I just find app for Roku and beta for iOS, and yes, the old apps (under the LBRY name) or will keep Desktop and Android apps under LBRY name?

Thanks.

**Comment by tzarebczan** [comment]
Odysee code is on the Odysee branch of the LBRY desktop repo.

There's an Android version in the works. For desktop, there may just be a desktop mode with odysee theme and features.
