### ISSUE TITLE
support `file xxx` calls

### ISSUE THREAD

**Issue by seanyesmunt** [lbryio/lbrytv#51]
I don't have a whole lot to add to this issue right now, but wanted to create it so it wasn't lost.

We are now using `streaming_url` in the desktop app that comes from `get` and `file_list`. We don't use these commands on lbry.tv.

Ideally we could just use the same calls and the lbrytv api server would change `streaming_url` to point at lbrytv streaming endpoint so we don't need checks in the code like this:
```
const source = IS_WEB
    ? `https://api.lbry.tv/content/claims/${claim.name}/${claim.claim_id}/stream`
    : streaming_url;
```

**Comment by sayplastic** [comment]
I can patch `get` and `file_list`. There's also a possibility that we won't be using lbrytv streaming and rely on SDK streaming instead. I'll research it in the next few days.

**Comment by kauffj** [comment]
Whenever feasible, the solution should be to patch the API calls rather than to modify the lbry-desktop code. `lbry-desktop` should attempt to not "know" lbry.tv exists to the extent that it is pragmatic and possible to do so.

**Comment by sayplastic** [comment]
@seanyesmunt would patching `get` in a way that would prevent it from downloading any actual files but return the correct `streaming_url` in response be enough to make this work?

**Comment by seanyesmunt** [comment]
That should work
