### ISSUE TITLE
LBRYtv should supply X-Forwarded-For to internal API calls 

### ISSUE THREAD

**Issue by andybeletsky** [lbryio/lbrytv#70]
@tzarebczan reported that user IPs logged in the Internal APIs database do not reflect actual addresses of users accessing the service. Internal API client should accept and forward `X-Forwarded-For` header coming with the user request.

**Comment by tzarebczan** [comment]
This is now happening more often with our recent changes of allowing passthrough on all unauthenticated calls. We should be able to pass the IP just like we do with the authenticated ones. It makes it harder to track proper accesses for rewards/abuse monitoring purposes. 

Not a huge priority, but if it's a quick one, let's try to knock it out.

**Comment by tzarebczan** [comment]
This is more annoying now that we have more ips

**Comment by andybeletsky** [comment]
Ok, tv API sends the correct `X-Forwarded-For` for remote client now. Example:

```
POST /user/has_verified_email HTTP/1.1
Host: localhost:9091
User-Agent: Go-http-client/1.1
Content-Length: 14
Accept: application/json
Content-Type: application/x-www-form-urlencoded
X-Forwarded-For: 127.0.0.1
Accept-Encoding: gzip
auth_token=abc%
```

@nikooo777 can you verify please?

**Comment by kauffj** [comment]
@nikooo777 I'm closing this as fixed, please re-open if there is an issue.
